apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: new-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: ybsid.azurecr.io/3d-portfolio:v0.0.1
          ports:
            - containerPort: 80
