apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: new-test
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ybsid@contact.com # Update with your email address
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik
