apiVersion: v1
kind: Service
metadata:
    name: portfolio-service
    namespace: deploy-demo
spec:
    selector:
        app: portfolio
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
