apiVersion: v1
kind: Service
metadata:
    name: 3d-portfolio
spec:
    type: LoadBalancer
    ports:
        - port: 3000 # port number to listen
          targerPort: 80 # pod port number
    selector:
        app: 3d-portfolio
