apiVersion: v1
kind: Service
metadata:
    name: 3d-portfolio-service
    kubernetes.io/service-name: 3d-portfolio-service
spec:
    type: LoadBalancer
    ports:
        - port: 3000 # port number to listen
          targerPort: 3d-portfolio # pod port number
    selector:
        app: 3d-portfolio
