name: Deploy to AKS

on: workflow_dispatch

env:
  IMAGE_NAME: 3d-portfolio
  TAG_NAME: v0.0.1
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  CLUSTER_NAME: deploy_test
  NAMESPACE: deploy-test
  RESOURCE_GROUP: aks_res_group

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_LOGIN_SERVER}}

      - name: Pull ACR image
        run: docker pull ${{secrets.ACR_LOGIN_SERVER}}/${{env.IMAGE_NAME}}:${{env.TAG_NAME}}

      - name: Login to Azure
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_LOGIN_CRED }}

      - name: Get AKS credentials and set context
        uses: azure/aks-set-context@v1
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          creds: ${{secrets.AZURE_LOGIN_CRED}}

      - name: Deploy to AKS namespace
        run: kubectl apply -n ${{ env.NAMESPACE }} -f /manifests/deployment.yml
