name: Build and push image

on: workflow_dispatch

env:
  IMAGE_NAME: 3d-portfolio
  TAG_NAME: v0.0.1
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  CLUSTER_NAME: deploy_test
  NAMESPACE: deploy-test
  RESOURCE_GROUP: aks_res_group

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{env.IMAGE_NAME}}:${{ env.TAG_NAME }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{env.IMAGE_NAME}}:${{env.TAG_NAME}}

      - name: Set context to AKS cluster
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_LOGIN_CRED }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          action: deploy
          manifests: |
            manifests/deployment.yml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}.azurecr.io/${{env.IMAGE_NAME}}:${{env.TAG_NAME}}
          namespace: ${{env.NAMESPACE}}
